#!/usr/bin/env python3
from const import AVAILABLE_BORDERS
from table import BasicTable


example_columns = [
    {
        "label": "Name",
        "width": 25,
        "align": "left",
    },
    {
        "label": "Email",
        "width": 32,
        "align": "centre",
    },
    {
        "label": "Years-of-Service",
        "align": "right",
    }
]

example_data = [
    ("Owen Klan", "oklan@example.com", 1),
    ("Barry Badlow", "bbadlow@example.com", 13),
    ("Genevive Goodhigh Really-Long-Named", "ggoodhigh@example.com", 2),
]


def main():
    print(("Simple test program, designed to demonstrate alignment of "
           "columns as well as border styles.\n"))
    print("Border styles are available from 'const.AVAILABLE_BORDERS' list.\n")
    for border_style in AVAILABLE_BORDERS:
        print(f"Table style: {border_style}")
        bt = BasicTable(columns=example_columns, border=border_style)

        for row in example_data:
            bt.add_row(row)

        print("\n".join(bt.render()))
        print("")


if __name__ == "__main__":
    main()
